Added Vault Token from Jenkins Credentials Store

diff --git a/Week-3/terraform-week3/Jenkinsfile b/Week-3/terraform-week3/Jenkinsfile
--- a/Week-3/terraform-week3/Jenkinsfile
+++ b/Week-3/terraform-week3/Jenkinsfile
@@ -7,6 +7,8 @@ options {
 }
 
     environment {
+        VAULT_ADDR = "http://18.118.27.69:8200/"
+        VAULT_TOKEN = credentials('vault-token') 
         ENV_DIR = "Week-3/terraform-week3/environments/dev"  // Change this for different environments
     }
 
@@ -24,7 +26,7 @@ options {
             steps {
                 script {
                     sh "pwd"  // Print the current directory
-                    sh "ls -l ${ENV_DIR} || echo '❌ ERROR: Directory ${ENV_DIR} does not exist!'" 
+                    sh "ls -l ${ENV_DIR} || echo 'ERROR: Directory ${ENV_DIR} does not exist!'" 
                 }
             }
         }
@@ -36,7 +38,7 @@ options {
                     if (dirExists == "exists") {
                         sh "cd ${ENV_DIR} && terraform init"
                     } else {
-                        error "❌ ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
+                        error "ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
                     }
                 }
             }
@@ -49,7 +51,7 @@ options {
     //                 if (dirExists == "exists") {
     //                     sh "cd ${ENV_DIR} && terraform apply -auto-approve"
     //                 } else {
-    //                     error "❌ ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
+    //                     error "ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
     //                 }
     //             }
     //         }
@@ -63,7 +65,7 @@ stage('Terraform Destroy') {
                     if (dirExists == "exists") {
                         sh "cd ${ENV_DIR} && terraform destroy -auto-approve"
                     } else {
-                        error "❌ ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
+                        error "ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
                     }
                 }
             }
@@ -72,10 +74,10 @@ stage('Terraform Destroy') {
     
     post {
         success {
-            echo "✅ Terraform applied successfully in ${ENV_DIR}!"
+            echo "Terraform applied successfully in ${ENV_DIR}!"
         }
         failure {
-            echo "❌ Terraform apply failed in ${ENV_DIR}!"
+            echo "Terraform apply failed in ${ENV_DIR}!"
         }
     }
 }
